# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Chirp2MQTT
version: "1.1.81"
slug: chirp2mqtt
description: HA add-on to incorporatex ChirpStack LoraWan devices into MQTT integration
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
url: "https://github.com/home-assistant/addons-example/tree/main/example"
startup: application
webui: http://[HOST]:[PORT:8080]
boot: auto
ports:
  8080/tcp: 8088
#  8099/tcp: 8099
  1700/udp: 1708
ports_description:
  8080/tcp: "ChirpStack server WEB UI port"
  1700/udp: "Port to receive LoraWAN packets"
homeassistant: "2024.3.1"
map:
  - homeassistant_config
  - addon_config
  - addons
  - share:rw
init: false
options:
  application_id: "72a56954-700f-4a52-90d2-86cf76df5c57"
  mqtt_user: "loramqtt"
  mqtt_password: "ploramqtt"
  discovery_prefix: "homeassistant"
  options_start_delay: 2
  options_restore_age: 4
  options_debug_print_payload: False
  log_level: "info"
schema:
  application_id: "str"
  mqtt_user: "str"
  mqtt_password: "str?"
  discovery_prefix: "str"
  options_start_delay: "int"
  options_restore_age: "int"
  options_debug_print_payload: bool
#  log_level: "match(debug|info|warning|error|fatal|critical)?"
  log_level: "str?"
timeout: 10
#image: "ghcr.io/home-assistant/chirp2mqtt-{arch}"
services:
  - mqtt:need
stage: experimental
ingress: true
#ingress_port: 8080
#ingress_entry: local-chirp2mqtt
